services:
  multi_vendor_event_management_redis:
      image: redis:7
      container_name: multi_vendor_event_management_redis
      ports:
        - "6378:6379"
  multi_vendor_event_management_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    env_file:
      - .env
    volumes:
      - multi_vendor_event_management_logs:/app/winston
      - /app/node_modules
      - .:/app
    depends_on:
      - multi_vendor_event_management_redis

  

volumes:
  multi_vendor_event_management_logs:
